# Generated by Django 5.1.3 on 2025-02-01 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='cielo_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='sale_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='vendor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='beeper',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cod_airline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='emisor_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='itinerary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='provider',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='reserv_system',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='special_services',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
