# Generated by Django 5.1.3 on 2025-02-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_budget_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
    ]
