# Generated by Django 5.1.3 on 2025-02-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_closedsales_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='special_services',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
